### ISSUE TITLE
Make blacklisted users in comfig

### ISSUE THREAD

**Issue by hail12pink** [TheCrazyInsanity/vmsaw#2]
https://github.com/TheCrazyInsanity/vmsaw/blob/b2c6cad5600d7ae1afc428977d392188ada97f84/index.js#L171
It would be better for these blacklisted users to be contained in an array inside of the config.

**Comment by TheCrazyInsanity** [comment]
probably

**Comment by TheCrazyInsanity** [comment]
https://github.com/TheCrazyInsanity/vmsaw/commit/90aa5cf7a8cdca989783c05e32da1e737ff503f1 added
